---
   name: 'installing services'
   hosts: localhost
   vars:
     packages:
       -httpd
       -maven
       -java
       -docker
   tasks:
     -
       yum:
         name: '{{ item }}'
         state: 'present'
       with_items: '{{ package }}' 
